# Install the pipeline's conda environment by running 
# the following command in your conda base environment:
# conda env create -f environment.yml

name: zero-to-hero-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib==3.6.2
  - scikit-learn>=1.1.3
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - shap=0.41.0
  - docopt=0.6.2
  - jinja2
  - altair_saver
  - altair=4.2.0
  - selenium<4.3.0
  - pandas=1.4.4
  - imbalanced-learn
  - pip
  - lightgbm
  - numpy=1.23.4
  - xgboost=1.7.1
  - pip:
    - joblib==1.1.0
    - dataframe-image==0.1.3
    - mglearn
    - psutil>=5.7.2
    - vl-convert-python
    - nltk